services:
  frontend:
    build:
      context: .
      dockerfile: src/WebDiffy.UI/Dockerfile
    image: web-diffy-ui:latest
    container_name: web-diffy-ui
    restart: unless-stopped
    ports:
      - "5011:5011"
    depends_on:
      - backend
    environment:
      - ASPNETCORE_HTTPS_PORTS= # leave empty to force http only
      - ASPNETCORE_HTTP_PORTS=5011
      - Api__Url=http://backend:5180
  backend:
    build:
      context: .
      dockerfile: src/WebPageChangeMonitor.Api/Dockerfile
    image: web-diffy-api:latest
    container_name: web-diffy-api
    restart: unless-stopped
    ports:
      - "5180:5180"
    environment:
      - ASPNETCORE_HTTPS_PORTS= # leave empty to force http only
      - ASPNETCORE_HTTP_PORTS=5180
      - ConnectionStrings__ChangeMonitor= # postgresql
      - ChangeMonitor__Notifications__AreEnabled=false
      - ChangeMonitor__Notifications__Channels__1__IsEnabled=false # pocprinthub
      - ChangeMonitor__Notifications__Channels__1__Url=
      - ChangeMonitor__Notifications__Channels__1__TenantId=
      - ChangeMonitor__Notifications__Channels__1__TenantToken=